// Swaps the Riot API key everywhere it is used, in one command:
//   pnpm riot:key RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx [--personal]
//
// 1. checks the key works (fresh development keys can take ~30 s to activate),
// 2. writes it to the local .env (RIOT_API_KEY, and RIOT_KEY_TYPE with --personal),
// 3. sets it on the Railway service (which redeploys it),
// 4. waits until the live server's /health reports the key as "ok".
// The key is never printed. Development keys can only be regenerated by hand at
// https://developer.riotgames.com (every 24 h); a personal key never expires.
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { railwayExecutable, railwaySpawnOptions } from "./railway-cli.mjs";

const SERVICE = "ldc-server";
const args = process.argv.slice(2);
const key = args.find((a) => !a.startsWith("--"))?.trim();
const personal = args.includes("--personal");
const skipRailway = args.includes("--local-only");

const fail = (msg) => {
  console.error(`✗ ${msg}`);
  process.exit(1);
};
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

if (!key || !/^RGAPI-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(key)) {
  fail("Usage: pnpm riot:key RGAPI-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx [--personal] [--local-only]");
}

const envText = readFileSync(".env", "utf8");
const platform = /^RIOT_PLATFORM=(\w+)/m.exec(envText)?.[1] ?? "euw1";

// 1. Does Riot accept it?
let ok = false;
for (let attempt = 1; attempt <= 7 && !ok; attempt++) {
  const res = await fetch(`https://${platform}.api.riotgames.com/lol/status/v4/platform-data`, { headers: { "X-Riot-Token": key } }).catch(() => null);
  if (res?.ok) ok = true;
  else if (res && (res.status === 401 || res.status === 403) && attempt < 7) {
    console.log(`… Riot doesn't accept the key yet (HTTP ${res.status}); new keys take a moment. Retrying in 5 s.`);
    await sleep(5_000);
  } else fail(`Riot rejected the key (${res ? `HTTP ${res.status}` : "network error"}). Copy it again from https://developer.riotgames.com.`);
}
console.log("✓ Riot accepts the key");

// 2. Local .env
const setLine = (text, name, value) =>
  new RegExp(`^${name}=.*$`, "m").test(text) ? text.replace(new RegExp(`^${name}=.*$`, "m"), `${name}=${value}`) : `${text.trimEnd()}\n${name}=${value}\n`;
let next = setLine(envText, "RIOT_API_KEY", key);
if (personal) next = setLine(next, "RIOT_KEY_TYPE", "personal");
writeFileSync(".env", next);
console.log(`✓ Updated .env${personal ? " (key type: personal)" : ""}`);
if (skipRailway) process.exit(0);

// 3. Railway (setting a variable redeploys the service)
const exe = railwayExecutable();
const deploymentStatus = () => {
  const out = spawnSync(exe, ["service", "status", "--service", SERVICE], railwaySpawnOptions(exe, { encoding: "utf8" })).stdout ?? "";
  return { id: /^Deployment: (\S+)/m.exec(out)?.[1] ?? null, status: /^Status: (\S+)/m.exec(out)?.[1] ?? null };
};
const current = spawnSync(exe, ["variables", "--service", SERVICE, "--kv"], railwaySpawnOptions(exe, { encoding: "utf8" })).stdout ?? "";
const sameKey = new RegExp(`^RIOT_API_KEY=${key}$`, "m").test(current) && (!personal || /^RIOT_KEY_TYPE=personal$/m.test(current));
if (sameKey) {
  console.log(`✓ Railway service ${SERVICE} already has this key; nothing to redeploy`);
  process.exit(0);
}
const before = deploymentStatus().id;
const setArgs = ["variables", "--service", SERVICE, "--set", `RIOT_API_KEY=${key}`, ...(personal ? ["--set", "RIOT_KEY_TYPE=personal"] : [])];
const r = spawnSync(exe, setArgs, railwaySpawnOptions(exe, { stdio: ["ignore", "ignore", "pipe"], encoding: "utf8" }));
if (r.status !== 0) fail(`Couldn't update Railway: ${(r.stderr ?? "").split("\n").find((l) => l.trim()) ?? "unknown error"} (is this folder linked? run railway status)`);
console.log(`✓ Set RIOT_API_KEY on Railway service ${SERVICE}; it is redeploying`);

// 4. Wait for the new deployment to go live, then check the key on /health.
const started = Date.now();
for (;;) {
  if (Date.now() - started > 10 * 60_000) fail(`Timed out waiting for the redeploy; check railway service status --service ${SERVICE}`);
  await sleep(10_000);
  const d = deploymentStatus();
  if (!d.id || d.id === before) continue;
  if (d.status === "FAILED" || d.status === "CRASHED") fail(`The redeploy ${d.status.toLowerCase()}; check railway logs --service ${SERVICE}`);
  if (d.status === "SUCCESS" || d.status === "SLEEPING") break;
}
const domain = /serviceDomains:\s*\{\s*"([^"]+)"/.exec(readFileSync(".railway/railway.ts", "utf8"))?.[1];
if (domain) {
  const h = await fetch(`https://${domain}/health`).then((x) => (x.ok ? x.json() : null)).catch(() => null);
  // Servers before 0.4.3 report riotKey as true/false.
  if (h?.riotKey === "ok" || h?.riotKey === true) console.log(`✓ https://${domain} is live with the new key (version ${h.version})`);
  else fail(`The server is up but reports riotKey: ${JSON.stringify(h?.riotKey)}`);
}
